{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ghostpass",
    "module": "gopass-kiosk-sdk-dev",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "devReleaseVariantDevReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-kiosk-sdk-dev-1.0.10.aar",
          "url": "gopass-kiosk-sdk-dev-1.0.10.aar",
          "size": 44764826,
          "sha512": "5be8332a40fa623d4ad087e8cb01f7767b9684b9338104c616d6c953f59cb8fb8eee0ca60a423948baa6c7664978b8b629ceabcac3ace07b49dbefa506b01292",
          "sha256": "416f298a128398d7dc3d9c8d642002fef8cd51f5b3e3c9d2671696b5517f08d7",
          "sha1": "79153ba6a25405b0d3aa32cf39ee0937f767f4ea",
          "md5": "b29a3bf70e7ad74381bba5ec60f5f0e7"
        }
      ]
    },
    {
      "name": "devReleaseVariantDevReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gopass-kiosk-sdk-dev-1.0.10.aar",
          "url": "gopass-kiosk-sdk-dev-1.0.10.aar",
          "size": 44764826,
          "sha512": "5be8332a40fa623d4ad087e8cb01f7767b9684b9338104c616d6c953f59cb8fb8eee0ca60a423948baa6c7664978b8b629ceabcac3ace07b49dbefa506b01292",
          "sha256": "416f298a128398d7dc3d9c8d642002fef8cd51f5b3e3c9d2671696b5517f08d7",
          "sha1": "79153ba6a25405b0d3aa32cf39ee0937f767f4ea",
          "md5": "b29a3bf70e7ad74381bba5ec60f5f0e7"
        }
      ]
    },
    {
      "name": "devReleaseVariantDevReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gopass-kiosk-sdk-dev-1.0.10-sources.jar",
          "url": "gopass-kiosk-sdk-dev-1.0.10-sources.jar",
          "size": 103618,
          "sha512": "21db199a830033faac8b22cebb6a197d45dece521dfff5466f6641f9b555ddff32ef8333b22373bae2e7c7cec47543571dc55c52339795087c9de59423f167b8",
          "sha256": "14ce1ce04297498ff8056f9525d902069831b541f2bac13152a1f3da0ed8b84a",
          "sha1": "626d7c4015932d6a22a5e5f2fdb99aa589cfe03c",
          "md5": "f111481c4afbb3d6367b8316ac72bfb4"
        }
      ]
    }
  ]
}
